name: Test

on:
  push:
    branches: [ $default-branch ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js setup
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm install
      - run: npm test

